#!/usr/bin/env bash
set -e
set -u
set -o pipefail
USAGE="

This script creates a database from a template.
Point it to the database to create from with the DB_ env variables."

: ${DB_HOST?You must provide an DB_HOST as an enviornment variable. "$USAGE"}
: ${DB_NAME?You must provide an DB_NAME as an enviornment variable. "$USAGE"}
: ${DB_USER?You must provide an DB_USER as an enviornment variable. "$USAGE"}
: ${DB_PASS?You must provide an DB_PASS as an enviornment variable. "$USAGE"}
DB_TEMPLATE=${DB_TEMPLATE:-template1}

# Fixes errors where connections are left open to the template
echo Dropping connections to database $DB_TEMPLATE on host $DB_HOST as user $DB_USER
PGPASSWORD="$DB_PASS" psql -P pager=off -d $DB_TEMPLATE -U $DB_USER -h $DB_HOST -c 'SELECT pid, pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = current_database() AND pid <> pg_backend_pid();'

echo Creating database $DB_NAME on host $DB_HOST from template $DB_TEMPLATE as user $DB_USER
PGPASSWORD="$DB_PASS" createdb -U $DB_USER -h $DB_HOST -T $DB_TEMPLATE $DB_NAME

