#!/usr/bin/env bash
set -e
set -u
set -o pipefail
set -a # makes all variables exported in the called script
USAGE="

This script drops and recreates a database from backup already restored to a template (using refresh_template).
Point it to the database to refresh to with the DB_ env variables.
Point it to the template to refresh from with the DB_TEMPLATE env variable."

: ${DB_TEMPLATE?You must provide DB_TEMPLATE as an enviornment variable. "$USAGE"}
: ${DB_NAME?You must provide DB_NAME as an enviornment variable. "$USAGE"}
: ${DB_HOST?You must provide DB_HOST as an enviornment variable. "$USAGE"}
: ${DB_USER?You must provide DB_USER as an enviornment variable. "$USAGE"}
: ${DB_PASS?You must provide DB_PASS as an enviornment variable. "$USAGE"}
./drop_db
./create_db
