#!/usr/bin/env bash
set -e
set -u
set -o pipefail
USAGE="

This script restores a database from a backup.
Point it to the backup to restore from with the \$BACKUP_DUMP env variable.
Point it to the server to restore to with the DB_ env variables."

: ${BACKUP_DUMP?You must provide an BACKUP_DUMP as an enviornment variable. "$USAGE"}
: ${DB_HOST?You must provide an DB_HOST as an enviornment variable. "$USAGE"}
: ${DB_NAME?You must provide an DB_NAME as an enviornment variable. "$USAGE"}
: ${DB_USER?You must provide an DB_USER as an enviornment variable. "$USAGE"}
: ${DB_PASS?You must provide an DB_PASS as an enviornment variable. "$USAGE"}

echo Restoring database $DB_NAME on host $DB_HOST as user $DB_USER from backup $BACKUP_DUMP
PGPASSWORD="$DB_PASS" pg_restore -U $DB_USER  -h $DB_HOST --no-owner --no-privileges --role=$DB_USER -d $DB_NAME /srv/postgres/backups/$BACKUP_DUMP

